language: python

python:
  - 3.6.1

install: 
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - postgresql

before_script:
  - psql -c 'create database shopping_list_api_test;' -U postgres

script:
  - nosetests --with-coverage --cover-package=server

after_success:
  - coveralls